# Generated by Django 5.2.4 on 2025-09-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('digital_x', models.CharField(max_length=10)),
                ('x01', models.IntegerField()),
                ('x001', models.IntegerField()),
                ('x0001', models.IntegerField()),
                ('x00001', models.IntegerField()),
                ('total', models.CharField(max_length=32)),
                ('detected_image_path', models.CharField(blank=True, default='', max_length=255)),
                ('digit_detect_path', models.CharField(blank=True, default='', max_length=255)),
                ('digit_summary_path', models.CharField(blank=True, default='', max_length=255)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meter_reader.meter')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['meter', '-timestamp'], name='meter_reade_meter_i_ff427d_idx')],
            },
        ),
    ]
